version: '3.8'

services:
  web:
    build: .
    command: python app/main.py
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .docker_env
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: process_image
    volumes:
      - postgres_data:/var/lib/postgresql/data


  celery_worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .docker_env
    depends_on:
      - redis
      - db

  redis:
    image: redis

volumes:
  postgres_data:
