version: '3.8'

services:
  web:
    build: .
    command: [ "/bin/sh", "database_migration/migrate.sh" ]
    volumes:
      - .:/app
    ports:
      - "8000:8080"
    env_file:
      - .docker_env
    restart: always
    depends_on:
      - db
      - redis
    networks:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_DB: process_image
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "4321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  celery_worker:
    build: .
    command: celery -A src.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .docker_env
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - backend

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    env_file:
      - .docker_env
    depends_on:
      - web
      - redis
      - celery_worker
    networks:
      - backend

  redis:
    image: redis
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true