"""new database

Revision ID: 0002
Revises: 0001
Create Date: 2024-06-29 20:02:40.765502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_versions',
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_image_versions_version_id'), 'image_versions', ['version_id'], unique=False)
    op.add_column('images', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('images', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_images_filename', table_name='images')
    op.drop_index('ix_images_project_id', table_name='images')
    op.create_foreign_key(None, 'images', 'projects', ['project_id'], ['id'])
    op.drop_column('images', 'versions')
    op.add_column('projects', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_column('projects', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('code', sa.CHAR(length=3), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'created_at')
    op.add_column('images', sa.Column('versions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.create_index('ix_images_project_id', 'images', ['project_id'], unique=False)
    op.create_index('ix_images_filename', 'images', ['filename'], unique=False)
    op.alter_column('images', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('images', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_index(op.f('ix_image_versions_version_id'), table_name='image_versions')
    op.drop_table('image_versions')
    # ### end Alembic commands ###
