"""change project to integer

Revision ID: 0003
Revises: 0002
Create Date: 2024-06-29 20:11:46.340284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE projects ALTER COLUMN name TYPE INTEGER USING name::integer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE projects ALTER COLUMN name TYPE VARCHAR USING name::varchar')

    # ### end Alembic commands ###
