"""Project model: id = project_id

Revision ID: 0006
Revises: 0005
Create Date: 2024-06-30 19:38:00.752244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projects_name_key', 'projects', type_='unique')
    op.drop_column('projects', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('name', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('projects_name_key', 'projects', ['name'])
    # ### end Alembic commands ###
